# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield
import edc_sync.models.password_field
import edc_sync.models.sync_model_mixin
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingTransaction',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('tx', models.BinaryField()),
                ('tx_name', models.CharField(db_index=True, max_length=64)),
                ('tx_pk', models.UUIDField(db_index=True)),
                ('producer', models.CharField(db_index=True, help_text='Producer name', max_length=200)),
                ('action', models.CharField(choices=[('I', 'Insert'), ('U', 'Update'), ('D', 'Delete')], max_length=1)),
                ('timestamp', models.CharField(db_index=True, max_length=50)),
                ('consumed_datetime', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('is_ignored', models.BooleanField(db_index=True, default=False, help_text='Ignore if update')),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('error', models.TextField(blank=True, max_length=1000, null=True)),
                ('batch_seq', models.IntegerField(blank=True, null=True)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('is_consumed', models.BooleanField(db_index=True, default=False)),
                ('is_self', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['timestamp', 'producer'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingTransaction',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('tx', models.BinaryField()),
                ('tx_name', models.CharField(db_index=True, max_length=64)),
                ('tx_pk', models.UUIDField(db_index=True)),
                ('producer', models.CharField(db_index=True, help_text='Producer name', max_length=200)),
                ('action', models.CharField(choices=[('I', 'Insert'), ('U', 'Update'), ('D', 'Delete')], max_length=1)),
                ('timestamp', models.CharField(db_index=True, max_length=50)),
                ('consumed_datetime', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('is_ignored', models.BooleanField(db_index=True, default=False, help_text='Ignore if update')),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('error', models.TextField(blank=True, max_length=1000, null=True)),
                ('batch_seq', models.IntegerField(blank=True, null=True)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('is_consumed_middleman', models.BooleanField(db_index=True, default=False)),
                ('is_consumed_server', models.BooleanField(db_index=True, default=False)),
                ('using', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Usually hostname-database_name. e.g mpp83-bhp041_survey', max_length=200, unique=True)),
                ('settings_key', models.CharField(help_text='Key in settings.DATABASES, usually hostname of producer', max_length=200, unique=True)),
                ('url', models.CharField(max_length=64)),
                ('db_host', models.CharField(blank=True, help_text='provide the IP address / hostname of the producer.', max_length=200, null=True, verbose_name='Producer host name.')),
                ('db_user', models.CharField(default='root', help_text='provide the database username of the producer.', max_length=25, null=True, verbose_name='Database username in Django settings.')),
                ('db_name', models.CharField(help_text='provide the database name of the producer.', max_length=25, null=True, verbose_name='Database name in Django settings.')),
                ('port', models.CharField(blank=True, default='', help_text='provide the database name of the producer.', max_length=25, null=True, verbose_name='Database port.')),
                ('db_password', edc_sync.models.password_field.PasswordModelField(help_text='provide the password to database on the producer. (Encryption: RSA local)', max_length=213, null=True, verbose_name='Database password.')),
                ('is_active', models.BooleanField(default=True)),
                ('sync_datetime', models.DateTimeField(null=True)),
                ('sync_status', models.CharField(default='-', max_length=250, null=True)),
                ('json_limit', models.IntegerField(default=0)),
                ('json_total_count', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(edc_sync.models.sync_model_mixin.SyncMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('request_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='complete', max_length=25)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc_sync.Producer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='producer',
            unique_together=set([('settings_key', 'is_active')]),
        ),
    ]
