# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingtransaction',
            name='is_ignored',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='is_ignored',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
