# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0002_auto_20160624_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingtransaction',
            name='consumer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='tx_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='consumer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='tx_name',
            field=models.CharField(max_length=64),
        ),
    ]
