# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0003_auto_20160624_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingtransaction',
            name='is_consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='is_self',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='is_consumed_middleman',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='is_consumed_server',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='using',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
