# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0004_auto_20160624_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=200, unique=True)),
                ('port', models.IntegerField(default='80')),
                ('api_name', models.CharField(default='v1', max_length=15)),
                ('format', models.CharField(default='json', max_length=15)),
                ('authentication', models.CharField(default='api_key', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, default='-', max_length=250, null=True)),
                ('comment', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['hostname', 'port'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=200, unique=True)),
                ('port', models.IntegerField(default='80')),
                ('api_name', models.CharField(default='v1', max_length=15)),
                ('format', models.CharField(default='json', max_length=15)),
                ('authentication', models.CharField(default='api_key', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, default='-', max_length=250, null=True)),
                ('comment', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['hostname', 'port'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('hostname', 'port')]),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set([('hostname', 'port')]),
        ),
    ]
