# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import edc_base.model.fields.uuid_auto_field


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0005_add_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(default='Gaborone', max_length=100)),
                ('remote_hostname', models.CharField(max_length=100)),
                ('remote_path', models.CharField(max_length=200)),
                ('archive_path', models.CharField(max_length=100, null=True)),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('filesize', models.FloatField(default=0.0)),
                ('filetimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('S', 'Sent'), ('F', 'Failed')], default='S', max_length=15)),
                ('sent_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('ack_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ack_user', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sent History',
                'ordering': ('-sent_datetime',),
                'verbose_name': 'Sent History',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
    ]
