# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0006_auto_20161109_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='ack_datetime',
            field=models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='sent_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='created',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='modified',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, editable=False),
        ),
    ]
