# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0006_auto_20160805_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='community',
        ),
        migrations.RemoveField(
            model_name='history',
            name='remote_hostname',
        ),
        migrations.AddField(
            model_name='history',
            name='location',
            field=models.CharField(default='gaborone', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='hostname_created',
            field=models.CharField(default='tsetsiba', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='hostname_created',
            field=models.CharField(default='tsetsiba', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='hostname_created',
            field=models.CharField(default='tsetsiba', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname_created',
            field=models.CharField(default='tsetsiba', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
    ]
