# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0008_auto_20170112_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='hostname_created',
            field=models.CharField(blank=True, default='tsetsiba', help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='hostname_created',
            field=models.CharField(blank=True, default='tsetsiba', help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='hostname_created',
            field=models.CharField(blank=True, default='tsetsiba', help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='hostname_created',
            field=models.CharField(blank=True, default='tsetsiba', help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname_created',
            field=models.CharField(blank=True, default='tsetsiba', help_text='System field. (modified on create only)', max_length=50),
        ),
    ]
