# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield
import edc_base.model.fields.uuid_auto_field


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0008_auto_20160809_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 9, 6, 16, 4, 66947, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='hostname_created',
            field=models.CharField(default='tsetsiba', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AddField(
            model_name='history',
            name='hostname_modified',
            field=edc_base.model.fields.hostname_modification_field.HostnameModificationField(default=datetime.datetime(2016, 8, 9, 6, 16, 4, 66947, tzinfo=utc), editable=False, help_text='System field. (modified on every save)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 9, 6, 16, 11, 208216, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='revision',
            field=django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision'),
        ),
        migrations.AddField(
            model_name='history',
            name='user_created',
            field=edc_base.model.fields.userfield.UserField(default='django', editable=False, max_length=50, verbose_name='user created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='user_modified',
            field=edc_base.model.fields.userfield.UserField(default=datetime.datetime(2016, 8, 9, 6, 22, 42, 655312, tzinfo=utc), editable=False, max_length=50, verbose_name='user modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together=set([('filename', 'sent_datetime')]),
        ),
    ]
