# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0009_auto_20160809_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
    ]
