# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0010_auto_20160809_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='hostname',
            field=models.CharField(default='community-server-1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='hostname_created',
            field=models.CharField(default='tsetsiba', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='hostname_created',
            field=models.CharField(default='tsetsiba', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='hostname_created',
            field=models.CharField(default='tsetsiba', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='hostname_created',
            field=models.CharField(default='tsetsiba', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname_created',
            field=models.CharField(default='tsetsiba', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
    ]
