# Generated by Django 2.0 on 2018-01-04 11:58

import _socket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0003_auto_20170518_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingtransaction',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='client',
            name='device_created',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='device_modified',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='history',
            name='device_created',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='history',
            name='device_modified',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='incomingtransaction',
            name='device_created',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='incomingtransaction',
            name='device_modified',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='device_created',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='device_modified',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='server',
            name='device_created',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='server',
            name='device_modified',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='history',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='incomingtransaction',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
    ]
