# Generated by Django 2.0.1 on 2018-01-25 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync', '0005_auto_20180116_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingtransaction',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
