# Generated by Django 2.1.4 on 2019-01-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("django_collect_offline", "0001_initial")]

    operations = [
        migrations.DeleteModel(name="History"),
        migrations.AlterUniqueTogether(name="client", unique_together=set()),
        migrations.AlterUniqueTogether(name="server", unique_together=set()),
    ]
